// figma: 395:357355 Button (450 variants)
const __variants = {
  "size=Large|colour=Primary|state=Fill|icon=Left": { backgroundColor: "var(--brand-primary)" },
  "size=Large|colour=Success|state=Fill|icon=Left": { backgroundColor: "var(--system-color-success)" },
  "size=Large|colour=Warning|state=Fill|icon=Left": { backgroundColor: "var(--system-color-warning)" },
  "size=Large|colour=Danger|state=Fill|icon=Left": { backgroundColor: "var(--system-color-danger)" },
  "size=Large|colour=Info|state=Fill|icon=Left": { backgroundColor: "var(--system-color-info)" },
  "size=Large|colour=Pink|state=Fill|icon=Left": { backgroundColor: "var(--system-color-pink)" },
  "size=Large|colour=Purple|state=Fill|icon=Left": { backgroundColor: "var(--system-color-purple)" },
  "size=Large|colour=Orange|state=Fill|icon=Left": { backgroundColor: "var(--system-color-orange)" },
  "size=Large|colour=Indigo|state=Fill|icon=Left": { backgroundColor: "var(--system-color-indigo)" },
  "size=Large|colour=Cyan|state=Fill|icon=Left": { backgroundColor: "var(--system-color-cyan)" },
  "size=Large|colour=Teal|state=Fill|icon=Left": { backgroundColor: "var(--system-color-teal)" },
  "size=Large|colour=Secondary|state=Fill|icon=Left": { backgroundColor: "var(--brand-secondry)" },
  "size=Large|colour=Primary|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--brand-primary)" },
  "size=Large|colour=Success|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-success)" },
  "size=Large|colour=Warning|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-warning)" },
  "size=Large|colour=Danger|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-danger)" },
  "size=Large|colour=Info|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-info)" },
  "size=Large|colour=Pink|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-pink)" },
  "size=Large|colour=Purple|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-purple)" },
  "size=Large|colour=Orange|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-orange)" },
  "size=Large|colour=Indigo|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-indigo)" },
  "size=Large|colour=Cyan|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-cyan)" },
  "size=Large|colour=Teal|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--system-color-teal)" },
  "size=Large|colour=Secondary|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--brand-secondry)" },
  "size=Large|colour=Light|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--brand-light)" },
  "size=Large|colour=Dark|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--brand-dark)" },
  "size=Large|colour=White|state=Outline|icon=Left": { backgroundColor: "revert", border: "1px solid var(--brand-white)" },
  "size=Large|colour=White|state=Fill|icon=Left": { backgroundColor: "var(--brand-white)" },
  "size=Large|colour=Dark|state=Fill|icon=Left": { backgroundColor: "var(--brand-dark)" },
  "size=XL|colour=Primary|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--brand-primary)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Success|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-success)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Warning|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-warning)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Danger|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-danger)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Info|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-info)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Pink|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-pink)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Purple|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-purple)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Orange|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-orange)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Indigo|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-indigo)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Cyan|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-cyan)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Teal|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--system-color-teal)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Secondary|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--brand-secondry)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Primary|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--brand-primary)",
  },
  "size=XL|colour=Success|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-success)",
  },
  "size=XL|colour=Warning|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-warning)",
  },
  "size=XL|colour=Danger|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-danger)",
  },
  "size=XL|colour=Info|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-info)",
  },
  "size=XL|colour=Pink|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-pink)",
  },
  "size=XL|colour=Purple|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-purple)",
  },
  "size=XL|colour=Orange|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-orange)",
  },
  "size=XL|colour=Indigo|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-indigo)",
  },
  "size=XL|colour=Cyan|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-cyan)",
  },
  "size=XL|colour=Teal|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--system-color-teal)",
  },
  "size=XL|colour=Secondary|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--brand-secondry)",
  },
  "size=XL|colour=Light|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--brand-light)",
  },
  "size=XL|colour=Dark|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--brand-dark)",
  },
  "size=XL|colour=White|state=Outline|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "revert",
    padding: "9px 16px 9px 16px",
    border: "1px solid var(--brand-white)",
  },
  "size=XL|colour=Light|state=Fill|icon=Left": { width: 131, height: 42, padding: "9px 16px 9px 16px" },
  "size=XL|colour=White|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--brand-white)",
    padding: "9px 16px 9px 16px",
  },
  "size=XL|colour=Dark|state=Fill|icon=Left": {
    width: 131,
    height: 42,
    backgroundColor: "var(--brand-dark)",
    padding: "9px 16px 9px 16px",
  },
  "size=Large|colour=Primary|state=Fill|icon=Right": { backgroundColor: "var(--brand-primary)" },
  "size=Large|colour=Success|state=Fill|icon=Right": { backgroundColor: "var(--system-color-success)" },
  "size=Large|colour=Warning|state=Fill|icon=Right": { backgroundColor: "var(--system-color-warning)" },
  "size=Large|colour=Danger|state=Fill|icon=Right": { backgroundColor: "var(--system-color-danger)" },
  // …+385 more variants
};
const __vkey = (p) => "size=" + p.size + '|' + "colour=" + p.colour + '|' + "state=" + p.state + '|' + "icon=" + p.icon;

export function Button2(_p = {}) {
  const props = { ..._p, size: _p.size ?? "Large", colour: _p.colour ?? "Light", state: _p.state ?? "Fill", icon: _p.icon ?? "Right" };
  const __vs = __variants[__vkey(props)] ?? {};
  return (
    <div className={props.className} style={{
      width: 119,
      height: 37,
      borderRadius: 5,
      backgroundColor: "var(--brand-light)",
      display: "flex",
      flexDirection: "row",
      gap: 8,
      padding: "8px 16px 8px 16px",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
      ...__vs, ...props.style,
    }}>
      <span style={{
        position: "absolute",
        left: 16,
        top: 8,
        width: 65,
        height: 21,
        fontFamily: "Nunito Sans",
        fontWeight: 500,
        fontSize: 14,
        textAlign: "center",
        lineHeight: "24px",
        color: "var(--grey-grey-900)",
      }}>Click Here</span>
      <div style={{
          position: "absolute",
          left: 89,
          top: 11.5,
          width: 14,
          height: 14,
        }} data-external={"chevron-right"} />
    </div>
  );
}
export default Button2;
